dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
sudo: false
install: ./mvnw clean
script: ./mvnw install site
notifications:
  email: false
before_install:
  - git submodule update --init --recursive
